dotbot/controller.py
dotbot/frontend/src/DotBots.js
dotbot/frontend/src/DotBotsMap.js
dotbot/models.py

controller: frontend: rework management of known dotbots

---

.github/workflows/continuous-integration.yml
tests_requirements.txt
tox.ini

This is a quick fix for the CI now that the default tox version is >=4.

ci: several fixes after tox update to 4.0.x

---

.gitignore
dotbot/controller.py
dotbot/protocol.py
dotbot/tests/test_protocol.py

controller: add logic for sending back computed lh2 position to the dotbot

---

dotbot/controller.py
dotbot/frontend/src/DotBots.js
dotbot/protocol.py
dotbot/tests/test_protocol.py

Add support for GPS position payloads

---

dotbot/frontend/src/DotBotsMap.js

DotBotMap: add checkbox to toggle grid display on the DotBot map

---

dotbot/frontend/src/DotBots.js
dotbot/frontend/src/Joystick.js
dotbot/frontend/src/rest.js

DotBots: add sliders to control SailBot rudder and sail

---

dotbot/controller.py
dotbot/frontend/src/DotBots.js
dotbot/frontend/src/DotBotsMap.js
dotbot/frontend/src/SailBotsMap.js
dotbot/models.py
dotbot/protocol.py
dotbot/tests/test_protocol.py

controller: frontend: add support for dotbot data message type, adapt UI with direction

---

dotbot/controller.py
dotbot/lighthouse2.py
dotbot/main.py
dotbot/tests/test_main.py

dotbot: use .pydotbot in home directory to store the lh2 calibration file

---

dotbot/serial_interface.py

serial: send large payloads in 64 bytes chunks

---

dotbot/controller.py
dotbot/frontend/src/DotBots.js
dotbot/frontend/src/DotBotsMap.js
dotbot/frontend/src/rest.js
dotbot/models.py
dotbot/protocol.py
dotbot/server.py
dotbot/tests/test_protocol.py
dotbot/tests/test_server.py

controller: frontend: add support for control mode (manual/auto) and LH2 waypoints

---

dotbot/controller.py
dotbot/models.py
dotbot/server.py
dotbot/tests/test_controller.py
dotbot/tests/test_server.py
pyproject.toml

This works with LH2 and GPS positions.
fixes #50 
depends on #49

controller: models: server: extend dotbot model with the history of positions

---

dotbot/controller.py
dotbot/frontend/package-lock.json
dotbot/frontend/package.json
dotbot/frontend/src/DotBots.js
dotbot/frontend/src/DotBots.test.js
dotbot/frontend/src/DotBotsMap.js
dotbot/frontend/src/SailBotsMap.js
dotbot/frontend/src/constants.js
dotbot/frontend/src/helpers.js
tox.ini

frontend: display position history on maps (DotBot and SailBot)

---

dotbot/protocol.py
dotbot/tests/test_protocol.py

protocol: raise an exception if version is not compatible

---

dotbot/models.py
dotbot/protocol.py

models: protocol: use IntEnum for Enum with int only values

---

dotbot/lighthouse2.py
dotbot/tests/test_lighthouse2.py
utils/hooks/sdist.py

lighthouse2: only rely on C library for counts computation

---

README.md
dotbot/controller.py
dotbot/hdlc.py
dotbot/main.py
dotbot/tests/test_hdlc_handler.py
dotbot/tests/test_main.py

Make Dotbot table in terminal optional

---

dotbot/frontend/src/DotBots.js
dotbot/frontend/src/rest.js
dotbot/server.py
dotbot/tests/test_server.py

server: frontend: add endpoint and UI for clearing position history

---

dotbot/frontend/src/DotBots.js
dotbot/frontend/src/DotBots.test.js
dotbot/frontend/src/DotBotsMap.js
dotbot/frontend/src/SailBotsMap.js

frontend: simplify waypoints selection and autonomous mode start/stop

---

dotbot/hdlc.py

fixes #72 
also add some test cases when escape bytes are present in the FCS part.

hdlc: escape FCS bytes if needed

---

dotbot/frontend/src/DotBots.js

frontend: add keyboard shortcuts event management for starting/stopping autonomous control

---

utils/logs/README.md
utils/logs/analyze_delays.py
utils/logs/requirements.txt

Adds a place where logs useful post analysis/parsing scripts could be put.

utils: add initial logs utility script

---

dotbot/protocol.py
dotbot/tests/test_protocol.py

protocol: refactor endianess handling in protocol and adapt tests

---

README.md
dotbot/controller.py
dotbot/main.py
dotbot/server.py
dotbot/tests/test_main.py
setup.cfg

controller: add basic gateway handshaking mechanism + minor logging improvements

---

README.md

README.md: add link to doc on readthedocs

---

dotbot/frontend/src/Joystick.js

frontend: fix joystick left/right direction

---

dotbot/joystick.py

joystick: fix invalid raw command parameters

---

.gitignore
dotbot/lib/.gitignore
dotbot/lib/CMakeLists.txt
utils/hooks/pydotbot_utils.py

lh2: fix C library build with Windows

---

dotbot/frontend/src/DotBots.js

JavaScript GUI bug: fixes #133

---

dotbot/controller.py
dotbot/sailbot_simulator.py

Tiny follow-up cleanup PR for #136

dotbot/sailbot_simulator: cleanup and small refactoring of the code

---

.pre-commit-config.yaml
dotbot/controller.py
dotbot/dotbot_simulator.py
dotbot/frontend/src/DotBotsMap.js
dotbot/lighthouse2.py
dotbot/protocol.py
dotbot/sailbot_simulator.py
dotbot/server.py
dotbot/tests/test_controller.py
dotbot/tests/test_lighthouse2.py
dotbot/tests/test_protocol.py
dotbot/tests/test_server.py
pyproject.toml

Refactor low-level protocol to enable layering

---

dotbot/controller.py
dotbot/dotbot_simulator.py
dotbot/edge_gateway.py
dotbot/edge_gateway_app.py
dotbot/protocol.py
dotbot/sailbot_simulator.py
dotbot/serial_interface.py
dotbot/tests/test_protocol.py

These changes are required with https://github.com/DotBots/swarmit/pull/16
Test case must be extended for the new protocol payload.

dotbot/protocol: make version compatible with blink. Add new raw data payload
